inherits: jiefangbei_60_base.yaml

experiment:
  name: jiefangbei_line30_base

outputs:
  root: outputs/line_bus/jiefangbei_30min

data:
  root: data/processed_line_bus/jiefangbei/30min
  pred_len: 6
  prev_lag: 48
