inherits: default.yaml

experiment:
  name: od_llm_qwen2_5_1_5b_local

model:
  name: od_llm
  rank: 4
  d_model: 64
  n_heads: 4
  dim_feedforward: 128
  dropout: 0.1
  max_tokens: 4096

  llm_model: qwen2.5-1.5b
  pretrained_path: "C:/Users/Mayn/Desktop/工作二/OD-LLM/hf_models/qwen2.5-1.5b"
  pretrained: true
  local_files_only: true
  trust_remote_code: true

  llm_dim: 1536
  llm_layers: 6
  llm_heads: 12
  freeze_llm: true
  use_reprogramming: true
  num_virtual_prompt_tokens: 8
